language: python

python: "3.8"

git:
  depth: 1

branches:
  only:
    - main

install:
  - pip install -r requirements.txt

script:
  - coverage run manage.py test polls

after_script:
  - bash <(curl -s https://codecov.io/bash)
