# Generated by Django 3.2.6 on 2021-10-25 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20211025_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
